---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ATTENDEE_SERVICE_URL:

inputs:
- name: movie-fun-pipeline

run:
  path: movie-fun-pipeline/ci/tasks/smoke-test.sh